# SPDX-FileCopyrightText: Copyright 2025 Siemens
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ".github/PULL_REQUEST_TEMPLATE.md"
SPDX-FileCopyrightText = "Copyright 2025 Siemens"
SPDX-License-Identifier = "Apache-2.0"
precedence = "override"

[[annotations]]
path = "demo/client/gta-key.pem"
SPDX-FileCopyrightText = "Copyright 2025 Siemens"
SPDX-License-Identifier = "Apache-2.0"
precedence = "override"